const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    FECTH_GENDER_START : 'FECTH_GENDER_START',
    FECTH_GENDER_SUCCESS:'FECTH_GENDER_SUCCESS',
    FECTH_GENDER_FAIDED :'FECTH_GENDER_FAIDED',

    FECTH_POSITION_START :'FECTH_POSITION_START',
    FECTH_POSITION_SUCCESS :'FECTH_POSITION_SUCCESS',
    FECTH_POSITION_FAIDED :'FECTH_POSITION_FAIDED',

    FECTH_ROLE_START :'FECTH_ROLE_START',
    FECTH_ROLE_SUCCESS :'FECTH_ROLE_SUCCESS',
    FECTH_ROLE_FAIDED :'FECTH_ROLE_FAIDED',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    USER_LOGIN_FAIL:'USER_LOGIN_FAIL'

})

export default actionTypes;